//! Test-only generation of TypeScript bindings for Rust IPC types.
//!
//! Connected-service DTOs are emitted separately, and cross-bundle references
//! fail generation.

// The aggregate includes desktop-only DTOs and is excluded from CLI builds.
#[cfg(all(test, feature = "desktop"))]
mod tests {
    use ts_rs::{Config, TS};

    use crate::checks::CheckResult;
    use crate::commands::scan::execution::{RunScanExecutionRequest, RunScanExecutionResult};
    use crate::commands::{
        ActionableDesktopNotificationRequest, BaselineDecisionResult, ConnectedAlert,
        ConnectedAlertCause, ConnectedAlertDelivery, ConnectedAlertElsewhere, ConnectedAlertFeed,
        ConnectedAlertWebhook, ConnectedCiToken, ConnectedCreatedAlertWebhook,
        ConnectedCreatedProviderConnection, ConnectedDestination, ConnectedDestinationDeletion,
        ConnectedDestinationWrite, ConnectedErasureReceipt, ConnectedImportResult,
        ConnectedInspection, ConnectedKeyRotation, ConnectedNotificationSettings,
        ConnectedNotificationSettingsWrite, ConnectedProviderConnection, ConnectedProviderProject,
        ConnectedProviderVerification, ConnectedReconnection, ConnectedRecoveryAnswer,
        ConnectedRemoteState, ConnectedReportLink, ConnectedReportRevocation, ConnectedReportRow,
        ConnectedRotatedAlertWebhook, ConnectedRotatedWebhookSecret, ConnectedScopeSyncResult,
        ConnectedServiceActivation, ConnectedSiteChallenge, ConnectedSiteCredential,
        ConnectedStatus, ConnectedSyncResult, ConnectedVerification, ConnectedVerificationResend,
        ConnectedWebhookSecret, ConnectedWebhookTest, CreateFixAttemptArgs,
        DashboardReferenceSignals, DashboardSnapshot, DesktopCommandResult, DesktopWatchRequest,
        DesktopWatchSignal, FixAttemptDto, IssueVerificationOutcome, ProjectNavBadgeSnapshot,
        ProjectSummary, ResolvedProjectPath, ScanScopeWriteResult, SiteBaseline,
        TodayProjectWorkSummary, UpdateCheckOutcome, UpdateInstallOutcome,
    };
    use crate::core::agent_tools::{AgentTool, AgentToolStatus};
    use crate::core::correlation::preview::{DeployRiskPreview, WhatIfResult};
    use crate::core::event_correlations::Correlation;
    use crate::core::git::{GitCommit, GitStatus};
    use crate::core::project::{DetectedUrl, ProjectInfo};
    use crate::core::scan_execution::{ScanExecutionDetail, ScanExecutionSummary};
    use crate::core::scanner::{
        MultiScanResult, ScanResult, ScheduledScanType, VerifyChecksResult,
    };
    use crate::core::sitemap::SitemapResult;
    use crate::core::types_work_items::{FixLocation, IssueGroup, PageSummary, ScoreSnapshot};
    use crate::db::alerts::{AlertFilter, AlertRow, UnreadAlertCounts};
    use crate::db::resolved_issues::ResolvedIssue;
    use crate::db::{
        CodeScanReportPayload, CodeScanResult, CodeScanSummary, ConsolidatedIssue,
        IssueCheckMemory, IssueLink, PageRecord, ProjectRecord, ProjectSignalSnapshot,
        ReportHistoryEntry, ScanSchedule, ScanSessionSummary, ScanSummary, ScoreSnapshotPoint,
        ScoreTrendPoint, SiteEvent, WebhookConfig,
    };
    use crate::integrations::github::GithubReleaseSummary;
    use crate::integrations::issue_tracker::IssueContext;
    use crate::integrations::pagespeed::PageSpeedReport;
    use crate::integrations::{IntegrationConfig, IntegrationData, IntegrationType};
    use crate::licensing::commands::LicenseInfo;
    use crate::report::{ReportBranding, ReportData, SectionConfig};
    use crate::ssl_probe::SslProbeResult;
    use crate::updates::types::UpdateReport;
    use crate::webview::analyzer::WebviewAnalysis;

    const GENERATED_NOTICE: &str = "\
// GENERATED by the ipc_bindings parity test from Rust types deriving ts_rs::TS.
// Do not edit by hand: change the Rust struct, run `cargo test`, commit the diff.
// Types live wherever they are defined (search: #[ts(export_to = \"ipc-bindings.ts\")]).";

    // Aggregate root that makes `export_all` traverse the complete IPC type graph.
    // `normalize_bundle` removes this synthetic type from generated output.
    #[derive(TS)]
    #[ts(export_to = "ipc-bindings.ts")]
    #[allow(dead_code)]
    struct IpcBindings {
        check_result: CheckResult,
        scan_result: ScanResult,
        multi_scan_result: MultiScanResult,
        run_scan_execution_request: RunScanExecutionRequest,
        run_scan_execution_result: RunScanExecutionResult,
        scan_execution_summary: ScanExecutionSummary,
        scan_execution_detail: ScanExecutionDetail,
        verify_checks_result: VerifyChecksResult,
        scheduled_scan_type: ScheduledScanType,
        project_info: ProjectInfo,
        detected_url: DetectedUrl,
        project_record: ProjectRecord,
        issue_group: IssueGroup,
        score_snapshot: ScoreSnapshot,
        fix_location: FixLocation,
        page_summary: PageSummary,
        issue_check_memory: IssueCheckMemory,
        issue_verification_outcome: IssueVerificationOutcome,
        site_event: SiteEvent,
        correlation: Correlation,
        scan_summary: ScanSummary,
        code_scan_summary: CodeScanSummary,
        score_trend_point: ScoreTrendPoint,
        score_snapshot_point: ScoreSnapshotPoint,
        resolved_issue: ResolvedIssue,
        code_scan_result: CodeScanResult,
        scan_session_summary: ScanSessionSummary,
        consolidated_issue: ConsolidatedIssue,
        project_summary: ProjectSummary,
        project_signal_snapshot: ProjectSignalSnapshot,
        today_project_work_summary: TodayProjectWorkSummary,
        dashboard_snapshot: DashboardSnapshot,
        dashboard_reference_signals: DashboardReferenceSignals,
        project_nav_badge_snapshot: ProjectNavBadgeSnapshot,
        sitemap_result: SitemapResult,
        page_record: PageRecord,
        desktop_watch_request: DesktopWatchRequest,
        desktop_watch_signal: DesktopWatchSignal,
        resolved_project_path: ResolvedProjectPath,
        actionable_desktop_notification_request: ActionableDesktopNotificationRequest,
        desktop_command_result: DesktopCommandResult,
        report_data: ReportData,
        report_branding: ReportBranding,
        section_config: SectionConfig,
        report_history_entry: ReportHistoryEntry,
        integration_config: IntegrationConfig,
        integration_data: IntegrationData,
        integration_type: IntegrationType,
        github_release_summary: GithubReleaseSummary,
        alert_row: AlertRow,
        alert_filter: AlertFilter,
        unread_alert_counts: UnreadAlertCounts,
        webview_analysis: WebviewAnalysis,
        scan_schedule: ScanSchedule,
        pagespeed_report: PageSpeedReport,
        code_scan_report_payload: CodeScanReportPayload,
        deploy_risk_preview: DeployRiskPreview,
        whatif_result: WhatIfResult,
        fix_attempt_dto: FixAttemptDto,
        create_fix_attempt_args: CreateFixAttemptArgs,
        issue_link: IssueLink,
        issue_context: IssueContext,
        agent_tool: AgentTool,
        agent_tool_status: AgentToolStatus,
        git_status: GitStatus,
        git_commit: GitCommit,
        webhook_config: WebhookConfig,
        update_report: UpdateReport,
        update_check_outcome: UpdateCheckOutcome,
        update_install_outcome: UpdateInstallOutcome,
        license_info: LicenseInfo,
        ssl_probe_result: SslProbeResult,
        site_baseline: SiteBaseline,
        baseline_decision_result: BaselineDecisionResult,
        connected_status: ConnectedStatus,
        connected_inspection: ConnectedInspection,
        connected_sync_result: ConnectedSyncResult,
        connected_scope_sync_result: ConnectedScopeSyncResult,
        connected_import_result: ConnectedImportResult,
        connected_site_challenge: ConnectedSiteChallenge,
        connected_remote_state: ConnectedRemoteState,
        connected_verification: ConnectedVerification,
        connected_ci_token: ConnectedCiToken,
        connected_service_activation: ConnectedServiceActivation,
        connected_erasure_receipt: ConnectedErasureReceipt,
        connected_report_link: ConnectedReportLink,
        connected_report_row: ConnectedReportRow,
        connected_report_revocation: ConnectedReportRevocation,
        connected_alert_feed: ConnectedAlertFeed,
        connected_alert: ConnectedAlert,
        connected_alert_cause: ConnectedAlertCause,
        connected_alert_delivery: ConnectedAlertDelivery,
        connected_alert_elsewhere: ConnectedAlertElsewhere,
        connected_alert_webhook: ConnectedAlertWebhook,
        connected_created_alert_webhook: ConnectedCreatedAlertWebhook,
        connected_rotated_alert_webhook: ConnectedRotatedAlertWebhook,
        connected_webhook_test: ConnectedWebhookTest,
        connected_destination: ConnectedDestination,
        connected_destination_write: ConnectedDestinationWrite,
        connected_destination_deletion: ConnectedDestinationDeletion,
        connected_verification_resend: ConnectedVerificationResend,
        connected_notification_settings: ConnectedNotificationSettings,
        connected_notification_settings_write: ConnectedNotificationSettingsWrite,
        connected_site_credential: ConnectedSiteCredential,
        connected_webhook_secret: ConnectedWebhookSecret,
        connected_rotated_webhook_secret: ConnectedRotatedWebhookSecret,
        connected_reconnection: ConnectedReconnection,
        connected_created_provider_connection: ConnectedCreatedProviderConnection,
        connected_provider_connection: ConnectedProviderConnection,
        connected_provider_project: ConnectedProviderProject,
        connected_provider_verification: ConnectedProviderVerification,
        connected_key_rotation: ConnectedKeyRotation,
        connected_recovery_answer: ConnectedRecoveryAnswer,
        scan_scope_write_result: ScanScopeWriteResult,
    }

    fn generated_path(file_name: &str) -> std::path::PathBuf {
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("desktop app root")
            .join("src")
            .join("generated")
            .join(file_name)
    }

    // Export deterministic local and connected IPC type bundles.
    // `split_blocks` rejects cross-boundary type dependencies.
    fn expected_bundles() -> (String, String) {
        let scratch = tempfile::tempdir().expect("scratch dir");
        // Match Tauri's JSON-number wire format for safe-range integer fields.
        let cfg = Config::new()
            .with_out_dir(scratch.path())
            .with_large_int("number");
        IpcBindings::export_all(&cfg).expect("export ipc bindings");
        let raw = std::fs::read_to_string(scratch.path().join("ipc-bindings.ts"))
            .expect("read generated bundle");
        let (main, connected) = split_blocks(bundle_blocks(&raw));
        (assemble_bundle(main), assemble_bundle(connected))
    }

    // The raw ts-rs output as trimmed blocks: ts-rs's own header dropped for
    // our regenerate notice, the `IpcBindings` aggregate stripped.
    fn bundle_blocks(raw: &str) -> Vec<String> {
        raw.split("\n\n")
            .map(str::trim)
            .filter(|block| !block.is_empty())
            .filter(|block| !block.starts_with("// This file was generated by"))
            .filter(|block| !block.contains("export type IpcBindings ="))
            .map(|block| {
                block
                    .lines()
                    .map(str::trim_end)
                    .collect::<Vec<_>>()
                    .join("\n")
            })
            .collect()
    }

    // The name a block exports. Blocks may open with `//` comment lines
    // (Rust doc comments come through ts-rs), so the declaration is found,
    // not assumed first.
    fn exported_name(block: &str) -> Option<&str> {
        let decl = block
            .lines()
            .find_map(|line| line.strip_prefix("export type "))?;
        Some(decl.split([' ', '=', '<']).next().unwrap_or(decl))
    }

    // Whether `block` mentions `name` as a whole identifier, not a prefix of
    // a longer one. Good enough for ts-rs output, which references types
    // verbatim and never inside strings.
    fn references(block: &str, name: &str) -> bool {
        block.match_indices(name).any(|(start, _)| {
            let before = block[..start].chars().next_back();
            let after = block[start + name.len()..].chars().next();
            let boundary = |c: Option<char>| c.is_none_or(|c| !c.is_alphanumeric() && c != '_');
            boundary(before) && boundary(after)
        })
    }

    // Partition main and connected bindings while rejecting cross-bundle references.
    fn split_blocks(blocks: Vec<String>) -> (Vec<String>, Vec<String>) {
        let is_connected =
            |block: &str| exported_name(block).is_some_and(|name| name.starts_with("Connected"));
        let (connected, main): (Vec<String>, Vec<String>) =
            blocks.into_iter().partition(|block| is_connected(block));
        for (own, other) in [(&main, &connected), (&connected, &main)] {
            for block in own.iter() {
                let body = block
                    .split_once('=')
                    .map(|(_, body)| body)
                    .unwrap_or(block.as_str());
                for name in other.iter().filter_map(|block| exported_name(block)) {
                    assert!(
                        !references(body, name),
                        "{} references {name} across the connected-bundle boundary; \
                         move one of them so each generated bundle stays self-contained",
                        exported_name(block).unwrap_or("a type"),
                    );
                }
            }
        }
        (main, connected)
    }

    fn assemble_bundle(blocks: Vec<String>) -> String {
        let mut body = String::new();
        let mut previous_was_one_line_alias = false;
        for block in blocks {
            let is_one_line_alias = !block.contains('\n') && block.starts_with("export type ");
            if !body.is_empty() {
                body.push_str(if previous_was_one_line_alias && is_one_line_alias {
                    "\n"
                } else {
                    "\n\n"
                });
            }
            body.push_str(&block);
            previous_was_one_line_alias = is_one_line_alias;
        }
        format!("{GENERATED_NOTICE}\n\n{body}\n")
    }

    fn normalize_bundle(raw: &str) -> String {
        assemble_bundle(bundle_blocks(raw))
    }

    #[test]
    fn normalized_bundle_has_no_trailing_line_whitespace() {
        let normalized = normalize_bundle(
            "// This file was generated by ts-rs.\n\nexport type Example = { value: string, \n/** docs */\nfield: string, };\n",
        );
        assert!(
            normalized.lines().all(|line| line == line.trim_end()),
            "generated bindings must stay clean under git diff --check: {normalized:?}"
        );
    }

    #[test]
    fn normalized_bundle_compacts_adjacent_one_line_aliases() {
        let normalized = normalize_bundle(
            "// This file was generated by ts-rs.\n\nexport type First = string;\n\nexport type Second = number;\n",
        );
        assert!(
            normalized.contains("export type First = string;\nexport type Second = number;"),
            "adjacent one-line aliases should not spend a blank line each: {normalized:?}"
        );
    }

    #[test]
    fn connected_bundle_boundary_refuses_a_cross_reference() {
        let entangled = vec![
            "export type ScanThing = { evidence: ConnectedProof, };".to_string(),
            "export type ConnectedProof = { value: string, };".to_string(),
        ];
        let crossed = std::panic::catch_unwind(|| split_blocks(entangled));
        assert!(
            crossed.is_err(),
            "a main-bundle type referencing a Connected* type must fail the split"
        );
        // The name check is a whole-identifier match: a type merely PREFIXED
        // by another's name is not a reference to it.
        let (main, connected) = split_blocks(vec![
            "export type Scan = { value: string, };".to_string(),
            "export type ConnectedScanner = { scans: Array<string>, };".to_string(),
        ]);
        assert_eq!(main.len(), 1);
        assert_eq!(connected.len(), 1);
    }

    // Regenerates stale frontend bindings, then fails so the diff is committed.
    #[test]
    fn ipc_bindings_ts_is_in_sync_with_rust_types() {
        let (expected_main, expected_connected) = expected_bundles();
        let mut stale = Vec::new();
        for (file_name, expected) in [
            ("ipc-bindings.ts", &expected_main),
            ("ipc-bindings-connected.ts", &expected_connected),
        ] {
            let target = generated_path(file_name);
            let actual = std::fs::read_to_string(&target).unwrap_or_default();
            if actual != *expected {
                let parent = target.parent().expect("generated dir");
                std::fs::create_dir_all(parent).expect("create generated dir");
                std::fs::write(&target, expected).expect("write generated bundle");
                stale.push(target.display().to_string());
            }
        }
        assert!(
            stale.is_empty(),
            "stale bindings regenerated at {}; re-run cargo test and commit the diff",
            stale.join(", ")
        );
    }
}
