use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn invoke_handler_command_names() -> BTreeSet<String> {
    let lib_src = include_str!("lib.rs");
    let handler_block = lib_src
        .split("tauri::generate_handler![")
        .nth(1)
        .expect("invoke_handler block")
        .split("])")
        .next()
        .expect("closing bracket");

    handler_block
        .lines()
        .filter_map(|l| l.trim().strip_suffix(','))
        .map(|l| l.rsplit("::").next().unwrap().trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn app_manifest_command_names() -> BTreeSet<String> {
    let build_src = include_str!("../build.rs");
    let app_block = build_src
        .split("APP_COMMANDS: &[&str] = &[")
        .nth(1)
        .expect("APP_COMMANDS block")
        .split("];")
        .next()
        .expect("closing bracket");

    app_block
        .lines()
        .filter_map(|l| {
            let l = l.trim().trim_end_matches(',');
            l.strip_prefix('"')
                .and_then(|s| s.strip_suffix('"'))
                .map(String::from)
        })
        .collect()
}

fn command_permissions_from_default_toml(src: &str) -> BTreeSet<String> {
    src.lines()
        .map(str::trim)
        .filter_map(|line| {
            let value = line.trim_end_matches(',').trim_matches('"');
            value
                .strip_prefix("allow-")
                .map(|command| command.replace('-', "_"))
        })
        .collect()
}

fn command_permissions_from_commands_allow(src: &str) -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    let mut in_allow_block = false;

    for line in src.lines().map(str::trim) {
        if line.starts_with("commands.allow = [") {
            if let Some(inline) = line
                .strip_prefix("commands.allow = [")
                .and_then(|value| value.strip_suffix(']'))
            {
                for command in inline.split(',') {
                    let command = command.trim().trim_matches('"');
                    if !command.is_empty() {
                        commands.insert(command.to_string());
                    }
                }
                continue;
            }
            in_allow_block = true;
            continue;
        }
        if in_allow_block && line == "]" {
            in_allow_block = false;
            continue;
        }
        if in_allow_block {
            let command = line.trim_end_matches(',').trim_matches('"');
            if !command.is_empty() {
                commands.insert(command.to_string());
            }
        }
    }

    commands
}

fn app_acl_command_permissions() -> BTreeSet<String> {
    let mut commands =
        command_permissions_from_default_toml(include_str!("../permissions/default.toml"));
    for src in [
        include_str!("../permissions/autogenerated/run_data_admin_command.toml"),
        include_str!("../permissions/autogenerated/run_external_connector_command.toml"),
        include_str!("../permissions/autogenerated/run_filesystem_access_command.toml"),
        include_str!("../permissions/autogenerated/run_filesystem_export_command.toml"),
        include_str!("../permissions/autogenerated/run_project_execution_command.toml"),
    ] {
        commands.extend(command_permissions_from_commands_allow(src));
    }
    commands
}

// Collect every direct command dispatched by a privileged broker.
fn broker_only_command_names() -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    for src in [
        include_str!("../permissions/data_admin.toml"),
        include_str!("../permissions/external_connectors.toml"),
        include_str!("../permissions/filesystem_access.toml"),
        include_str!("../permissions/filesystem_export.toml"),
        include_str!("../permissions/project_execution.toml"),
    ] {
        commands.extend(command_permissions_from_commands_allow(src));
    }
    for scope in [
        crate::commands::DATA_ADMIN_COMMANDS,
        crate::commands::EXTERNAL_CONNECTOR_COMMANDS,
        crate::commands::FILESYSTEM_ACCESS_COMMANDS,
        crate::commands::FILESYSTEM_EXPORT_COMMANDS,
        crate::commands::PROJECT_EXECUTION_COMMANDS,
    ] {
        commands.extend(scope.iter().map(|command| command.to_string()));
    }
    commands
}

fn broker_only_commands_in(surface: &BTreeSet<String>) -> Vec<String> {
    broker_only_command_names()
        .into_iter()
        .filter(|command| surface.contains(command))
        .collect()
}

fn command_security_manifest() -> serde_json::Value {
    serde_json::from_str(include_str!("../permissions/command-security.json"))
        .expect("valid command-security.json")
}

fn manifest_string_array(manifest: &serde_json::Value, key: &str) -> BTreeSet<String> {
    manifest
        .get(key)
        .and_then(|value| value.as_array())
        .unwrap_or_else(|| panic!("{} array missing from command-security.json", key))
        .iter()
        .map(|value| {
            value
                .as_str()
                .unwrap_or_else(|| panic!("{} must contain strings", key))
                .to_string()
        })
        .collect()
}

struct NativeConfirmationStep {
    function: String,
    requires: String,
}

struct NativeConfirmationContract {
    command: String,
    source: String,
    steps: Vec<NativeConfirmationStep>,
}

fn native_confirmed_manifest_entries() -> Vec<NativeConfirmationContract> {
    command_security_manifest()
        .get("nativeConfirmedCommands")
        .and_then(|value| value.as_array())
        .expect("nativeConfirmedCommands array")
        .iter()
        .map(|entry| {
            let command = entry
                .get("command")
                .and_then(|value| value.as_str())
                .expect("nativeConfirmedCommands command")
                .to_string();
            let source = entry
                .get("source")
                .and_then(|value| value.as_str())
                .expect("nativeConfirmedCommands source")
                .to_string();
            let steps = match entry.get("confirmationPath") {
                Some(value) => value
                    .as_array()
                    .filter(|path| !path.is_empty())
                    .expect("nativeConfirmedCommands confirmationPath must be a non-empty array")
                    .iter()
                    .map(|step| NativeConfirmationStep {
                        function: step
                            .get("function")
                            .and_then(|value| value.as_str())
                            .expect("nativeConfirmedCommands confirmationPath function")
                            .to_string(),
                        requires: step
                            .get("requires")
                            .and_then(|value| value.as_str())
                            .expect("nativeConfirmedCommands confirmationPath requires")
                            .to_string(),
                    })
                    .collect(),
                None => {
                    let function = entry
                        .get("confirmationFunction")
                        .and_then(|value| value.as_str())
                        .map(str::to_string)
                        .unwrap_or_else(|| command.clone());
                    let requires = entry
                        .get("requires")
                        .and_then(|value| value.as_str())
                        .expect("nativeConfirmedCommands requires")
                        .to_string();
                    vec![NativeConfirmationStep { function, requires }]
                }
            };
            NativeConfirmationContract {
                command,
                source,
                steps,
            }
        })
        .collect()
}

fn rust_source_files(dir: &Path, files: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            rust_source_files(&path, files);
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            files.push(path);
        }
    }
}

/// Source with any inline test module removed. Finds the first
/// `#[cfg(test)]` attribute that is followed, after optional whitespace and
/// other attribute lines, by `mod <ident> {` (a module with a body), and
/// returns everything before it. A `#[cfg(test)] mod tests;` declaration, or
/// a `#[cfg(test)]` on a `use`, field, or function, does not match, so it
/// cannot truncate a file's production code. Returns the source unchanged
/// when no inline test module is present. Source-scanning guardrails use
/// this so an inline test module's contents do not count as production.
fn production_half(source: &str) -> &str {
    let inline_test_module = regex::Regex::new(
        r"#\[cfg\(test\)\](?:\s*#\[[^\]]*\])*\s*mod\s+[A-Za-z_][A-Za-z0-9_]*\s*\{",
    )
    .expect("inline test module pattern");
    match inline_test_module.find(source) {
        Some(found) => &source[..found.start()],
        None => source,
    }
}

fn tracing_instrument_attributes(source: &str) -> Vec<(usize, &str)> {
    let marker = concat!("#[", "tracing::instrument");
    let mut attributes = Vec::new();
    let mut index = 0;

    while let Some(relative_start) = source[index..].find(marker) {
        let start = index + relative_start;
        let Some(relative_end) = source[start..].find(']') else {
            break;
        };
        let end = start + relative_end + 1;
        let line = source[..start].lines().count() + 1;
        attributes.push((line, &source[start..end]));
        index = end;
    }

    attributes
}

fn tracing_field_assignment_is_unsafe(attribute: &str) -> bool {
    let normalized: String = attribute
        .to_ascii_lowercase()
        .chars()
        .filter(|ch| !ch.is_whitespace())
        .collect();
    if !normalized.contains("fields(") {
        return false;
    }

    let unsafe_fields = [
        "raw",
        "password",
        "passwd",
        "secret",
        "token",
        "api_key",
        "apikey",
        "credential",
        "authorization",
        "database_url",
        "db_url",
        "path",
        "src_path",
        "dest_path",
        "source_path",
        "project_path",
        "project_root",
        "env_file_path",
        "working_dir",
    ];

    unsafe_fields.iter().any(|field| {
        normalized.contains(&format!("fields({}=", field))
            || normalized.contains(&format!(",{}=", field))
    })
}

// Extract functions carrying bare or conditional Tauri command attributes.
fn tauri_command_annotated_fn_names(source: &str) -> Vec<String> {
    let attribute_marker = concat!("tauri", "::command");
    let lines: Vec<&str> = source.lines().collect();
    let mut names = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("#[") || !trimmed.contains(attribute_marker) {
            continue;
        }
        // Allow a few intervening attributes (e.g. tracing::instrument)
        // between the annotation and the fn signature.
        for following in lines.iter().skip(index + 1).take(8) {
            if let Some(name) = fn_name_in_signature_line(following) {
                names.push(name);
                break;
            }
        }
    }
    names
}

fn fn_name_in_signature_line(line: &str) -> Option<String> {
    let mut tokens = line.split_whitespace();
    tokens.find(|token| *token == "fn")?;
    let name: String = tokens
        .next()?
        .chars()
        .take_while(|ch| ch.is_ascii_alphanumeric() || *ch == '_')
        .collect();
    (!name.is_empty()).then_some(name)
}

fn function_body_contains(source: &str, fn_name: &str, needle: &str) -> bool {
    let marker = format!("fn {}", fn_name);
    let mut search_start = 0;

    while let Some(relative_start) = source[search_start..].find(&marker) {
        let signature_start = search_start + relative_start;
        let tail_start = signature_start + marker.len();
        if source[tail_start..]
            .chars()
            .next()
            .is_some_and(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        {
            search_start = tail_start;
            continue;
        }
        let Some(boundary_offset) = source[tail_start..].find([';', '{']) else {
            return false;
        };
        let boundary = tail_start + boundary_offset;
        if source.as_bytes()[boundary] == b';' {
            search_start = boundary + 1;
            continue;
        }

        let mut depth = 0usize;
        let mut body_closed = false;
        for (offset, ch) in source[boundary..].char_indices() {
            if ch == '{' {
                depth += 1;
            } else if ch == '}' {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    if source[boundary..boundary + offset].contains(needle) {
                        return true;
                    }
                    search_start = boundary + offset + 1;
                    body_closed = true;
                    break;
                }
            }
        }
        if !body_closed {
            return false;
        }
    }

    false
}

#[test]
fn function_body_match_skips_declarations_and_name_prefixes() {
    let source = r#"
        trait Ports { async fn confirm_replacement(&self); }
        fn confirm_replacement_preview() { confirm_sensitive_action(); }
        impl Ports for DesktopPorts {
            async fn confirm_replacement(&self) { confirm_sensitive_action(); }
        }
    "#;

    assert!(function_body_contains(
        source,
        "confirm_replacement",
        "confirm_sensitive_action("
    ));
    assert!(!function_body_contains(
        "async fn confirm_replacement() {",
        "confirm_replacement",
        "confirm_sensitive_action("
    ));
}

// Guard: the `APP_COMMANDS` list in `build.rs` must contain every
// `#[tauri::command]` handler registered in `invoke_handler!`. If they
// drift, the ACL manifest won't gate the new command - any webview can
// call it.
#[test]
fn app_commands_list_matches_invoke_handler() {
    let lib_cmds = invoke_handler_command_names();
    let build_cmds = app_manifest_command_names();

    let missing_in_build: Vec<_> = lib_cmds.difference(&build_cmds).collect();
    let missing_in_lib: Vec<_> = build_cmds.difference(&lib_cmds).collect();
    assert!(
        missing_in_build.is_empty() && missing_in_lib.is_empty(),
        "APP_COMMANDS and invoke_handler! drifted.\n  in lib.rs but not build.rs: {:?}\n  in build.rs but not lib.rs: {:?}",
        missing_in_build,
        missing_in_lib,
    );
}

#[test]
fn csp_blocks_unsafe_inline_in_style_src() {
    let conf: serde_json::Value = serde_json::from_str(include_str!("../tauri.conf.json"))
        .expect("tauri.conf.json must parse");
    let csp = conf
        .pointer("/app/security/csp")
        .and_then(|v| v.as_str())
        .expect("CSP must be defined in tauri.conf.json");

    let style_src = csp
        .split(';')
        .map(str::trim)
        .find(|d| d.starts_with("style-src ") || *d == "style-src")
        .expect("CSP must declare a style-src directive");
    assert!(
        !style_src.contains("'unsafe-inline'"),
        "style-src must not contain 'unsafe-inline': got {style_src:?}"
    );

    // Defense in depth: also forbid 'unsafe-eval' anywhere.
    assert!(
        !csp.contains("'unsafe-eval'"),
        "CSP must not contain 'unsafe-eval' anywhere"
    );
}

#[test]
fn dev_csp_is_defined_and_blocks_unsafe_eval() {
    let conf: serde_json::Value = serde_json::from_str(include_str!("../tauri.dev.conf.json"))
        .expect("tauri.dev.conf.json must parse");
    let csp = conf
        .pointer("/app/security/csp")
        .and_then(|v| v.as_str())
        .expect("CSP must be defined in tauri.dev.conf.json");

    let forbidden_eval_directive = format!("'{}'", "unsafe-eval");
    assert!(
        !csp.contains(&forbidden_eval_directive),
        "dev CSP must not contain {forbidden_eval_directive}"
    );
    let script_src = csp
        .split(';')
        .map(str::trim)
        .find(|d| d.starts_with("script-src "))
        .expect("dev CSP must declare a script-src directive");
    assert!(
        script_src.contains("'self'"),
        "dev CSP script-src must include 'self': got {script_src:?}"
    );
}

#[test]
fn app_acl_permissions_cover_registered_commands() {
    let build_cmds = app_manifest_command_names();
    let acl_cmds = app_acl_command_permissions();

    let missing_from_acl: Vec<_> = build_cmds.difference(&acl_cmds).collect();
    let unknown_in_acl: Vec<_> = acl_cmds.difference(&build_cmds).collect();
    assert!(
        missing_from_acl.is_empty() && unknown_in_acl.is_empty(),
        "Tauri ACL permissions drifted from APP_COMMANDS.\n  in build.rs but not ACL: {:?}\n  in ACL but not build.rs: {:?}",
        missing_from_acl,
        unknown_in_acl,
    );
}

// Keep broker-only privileged commands off the direct Tauri IPC surface.
#[test]
fn broker_only_commands_are_not_registered_ipc_commands() {
    let broker_only = broker_only_command_names();
    assert!(
        broker_only.len() >= 50,
        "broker-only command list parsed suspiciously small: {:?}",
        broker_only,
    );

    let handler_leaks = broker_only_commands_in(&invoke_handler_command_names());
    let manifest_leaks = broker_only_commands_in(&app_manifest_command_names());
    assert!(
        handler_leaks.is_empty() && manifest_leaks.is_empty(),
        "Broker-only privileged commands must stay off the Tauri IPC surface; route them through their run_* broker instead.\n  in lib.rs invoke_handler!: {:?}\n  in build.rs APP_COMMANDS: {:?}",
        handler_leaks,
        manifest_leaks,
    );
}

// Negative control: prove the guard above flags a broker-only command that
// reappears on the IPC surface.
#[test]
fn broker_only_registration_guard_detects_reintroduced_commands() {
    let mut surface = invoke_handler_command_names();
    surface.insert("delete_project".to_string());
    assert_eq!(
        broker_only_commands_in(&surface),
        vec!["delete_project".to_string()],
    );
}

#[test]
fn broker_only_commands_carry_no_tauri_command_attribute() {
    let broker_only = broker_only_command_names();
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    assert!(!files.is_empty(), "Rust source scan found no files");

    let mut findings = Vec::new();
    for file in files {
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        for name in tauri_command_annotated_fn_names(&source) {
            if broker_only.contains(&name) {
                let relative = file
                    .strip_prefix(env!("CARGO_MANIFEST_DIR"))
                    .unwrap_or(&file)
                    .display();
                findings.push(format!("{}: {}", relative, name));
            }
        }
    }

    assert!(
        findings.is_empty(),
        "Broker-only privileged commands are dispatched as plain Rust calls by the run_* brokers and must not carry the Tauri command attribute; remove it: {:?}",
        findings,
    );
}

// Negative control: prove the annotation scan sees a broker-only command
// that regains the attribute, in both the bare and cfg_attr forms.
#[test]
fn broker_only_annotation_guard_detects_reannotated_commands() {
    let bare = format!(
        "#[{}]\npub async fn delete_project() {{}}\n",
        concat!("tauri", "::command"),
    );
    assert_eq!(
        tauri_command_annotated_fn_names(&bare),
        vec!["delete_project".to_string()],
    );

    let cfg_attr = format!(
        "#[cfg_attr(feature = \"desktop\", {})]\n#[tracing::instrument(skip_all)]\npub fn run_code_scan() {{}}\n",
        concat!("tauri", "::command"),
    );
    assert_eq!(
        tauri_command_annotated_fn_names(&cfg_attr),
        vec!["run_code_scan".to_string()],
    );
}

#[test]
fn git_is_spawned_only_by_the_hardened_runner() {
    let spawn = regex::Regex::new(r#"Command::new\(\s*"(?:[^"]*/)?git(?:\.exe)?"\s*\)"#)
        .expect("git spawn pattern");
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);
    assert!(!files.is_empty(), "Rust source scan found no files");

    let mut findings = Vec::new();
    let mut runner_spawns = 0;
    for file in files {
        let relative = file
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(&file)
            .display()
            .to_string();
        if relative.ends_with("_tests.rs") {
            continue;
        }
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        let hits = spawn.find_iter(production_half(&source)).count();
        if relative == "src/core/git.rs" {
            runner_spawns = hits;
        } else if hits > 0 {
            findings.push(format!("{relative} ({hits})"));
        }
    }

    assert_eq!(
        runner_spawns, 1,
        "src/core/git.rs must spawn git exactly once, inside hardened_git_command"
    );
    assert!(
        findings.is_empty(),
        "git must be spawned only through core::git::run_git so every invocation carries the config and environment hardening: {:?}",
        findings,
    );
}

// Negative control: the spawn pattern sees absolute and .exe forms.
#[test]
fn git_spawn_guard_detects_every_spelling() {
    let spawn = regex::Regex::new(r#"Command::new\(\s*"(?:[^"]*/)?git(?:\.exe)?"\s*\)"#)
        .expect("git spawn pattern");
    for source in [
        r#"Command::new("git")"#,
        r#"std::process::Command::new("/usr/bin/git")"#,
        r#"tokio::process::Command::new( "git.exe" )"#,
    ] {
        assert!(spawn.is_match(source), "{source}");
    }
    assert!(!spawn.is_match(r#"Command::new("gitleaks")"#));
}

// Negative control: an external test-module declaration must not truncate
// the production code that follows it.
#[test]
fn production_half_keeps_code_after_an_external_test_module_declaration() {
    let source = concat!(
        "#[cfg(test)]\n",
        "mod tests;\n",
        "\n",
        "fn spawn_git() {\n",
        "    Command::new(\"git\");\n",
        "}\n",
    );
    assert!(
        production_half(source).contains(r#"Command::new("git")"#),
        "an external test module declaration must not truncate production code"
    );
}

#[test]
fn production_half_strips_an_inline_test_module() {
    let source = concat!(
        "fn production() {}\n",
        "\n",
        "#[cfg(test)]\n",
        "mod tests {\n",
        "    fn spawn_git() {\n",
        "        Command::new(\"git\");\n",
        "    }\n",
        "}\n",
    );
    let half = production_half(source);
    assert!(half.contains("fn production"));
    assert!(
        !half.contains(r#"Command::new("git")"#),
        "an inline test module's contents must be stripped"
    );
}

#[test]
fn elevated_commands_are_not_in_baseline_acl() {
    let default_cmds =
        command_permissions_from_default_toml(include_str!("../permissions/default.toml"));
    let manifest = command_security_manifest();
    let elevated_cmds = manifest_string_array(&manifest, "elevatedCommands");

    let leaked_to_default: Vec<_> = elevated_cmds
        .iter()
        .filter(|command| default_cmds.contains(command.as_str()))
        .collect();
    assert!(
        leaked_to_default.is_empty(),
        "Elevated commands must stay out of the baseline ACL: {:?}",
        leaked_to_default,
    );
}

#[test]
fn sensitive_capability_groups_elevated_acl_surfaces() {
    let default_capability = include_str!("../capabilities/default.json");
    assert!(
        !default_capability.contains("\"opener:default\""),
        "Do not grant the main renderer an opener default."
    );
    for permission in [
        "core:window:allow-create",
        "core:webview:allow-create-webview-window",
    ] {
        assert!(
            !default_capability.contains(permission),
            "Baseline renderer capability must not allow renderer-created windows/webviews: {}",
            permission,
        );
    }
    assert!(
        !default_capability.contains("opener:"),
        "The main renderer must not have a generic URL opener; external links cross the native-confirmed broker."
    );

    let sensitive_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("capabilities")
        .join("sensitive.json");
    assert!(
        !sensitive_path.exists(),
        "Do not reintroduce one broad sensitive.json capability; keep elevated surfaces split by feature."
    );

    let manifest = command_security_manifest();
    let elevated_permissions = manifest_string_array(&manifest, "elevatedPermissions");
    let forbidden_main_plugin_permissions =
        manifest_string_array(&manifest, "forbiddenMainWindowPluginPermissions");
    assert!(
        forbidden_main_plugin_permissions.contains("keyring:default")
            && forbidden_main_plugin_permissions.contains("updater:default"),
        "command-security.json must list renderer-forbidden plugin defaults."
    );
    for permission in &forbidden_main_plugin_permissions {
        assert!(
            !default_capability.contains(permission.as_str()),
            "Baseline renderer capability must not grant plugin permission: {}",
            permission,
        );
    }
    let elevated_capabilities = [
        (
            "sitecmd-data-admin",
            include_str!("../capabilities/data-admin.json"),
        ),
        (
            "sitecmd-external-connectors",
            include_str!("../capabilities/external-connectors.json"),
        ),
        (
            "sitecmd-filesystem-access",
            include_str!("../capabilities/filesystem-access.json"),
        ),
        (
            "sitecmd-filesystem-export",
            include_str!("../capabilities/filesystem-export.json"),
        ),
        (
            "sitecmd-project-execution",
            include_str!("../capabilities/project-execution.json"),
        ),
    ];

    for (permission, capability) in elevated_capabilities {
        assert!(
            elevated_permissions.contains(permission),
            "Feature-scoped capability must be listed in command-security.json: {}",
            permission,
        );
        assert!(
            capability.contains(permission),
            "Feature-scoped capability is missing {}",
            permission,
        );
        for other_permission in elevated_permissions
            .iter()
            .filter(|other| other.as_str() != permission)
        {
            assert!(
                !capability.contains(other_permission.as_str()),
                "Feature-scoped capability for {} must not bundle {}",
                permission,
                other_permission,
            );
        }
    }
}

#[test]
fn high_risk_commands_require_native_confirmation() {
    let mut missing_confirmations = Vec::new();
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .expect("repo root");
    for entry in native_confirmed_manifest_entries() {
        let path = repo_root.join(&entry.source);
        let source = std::fs::read_to_string(&path).expect("read command source");
        for step in &entry.steps {
            if !function_body_contains(&source, &step.function, &step.requires) {
                missing_confirmations.push(format!(
                    "{}::{} ({})",
                    entry.source, entry.command, step.function
                ));
            }
        }
    }

    assert!(
        missing_confirmations.is_empty(),
        "High-risk IPC commands must require native confirmation before destructive or executable work: {:?}",
        missing_confirmations,
    );
}

#[test]
fn data_admin_commands_are_native_confirmed_in_manifest() {
    let data_admin_commands =
        command_permissions_from_commands_allow(include_str!("../permissions/data_admin.toml"));
    let confirmed_commands: BTreeSet<String> = native_confirmed_manifest_entries()
        .into_iter()
        .map(|entry| entry.command)
        .collect();

    let unconfirmed_data_admin_commands: Vec<_> = data_admin_commands
        .difference(&confirmed_commands)
        .collect();
    assert!(
        unconfirmed_data_admin_commands.is_empty(),
        "Data-admin commands must be native-confirmed in command-security.json: {:?}",
        unconfirmed_data_admin_commands,
    );
}

#[test]
fn elevated_acl_commands_are_listed_in_security_manifest() {
    let manifest = command_security_manifest();
    let manifest_commands = manifest_string_array(&manifest, "elevatedCommands");
    let mut acl_commands = BTreeSet::new();
    for src in [
        include_str!("../permissions/data_admin.toml"),
        include_str!("../permissions/external_connectors.toml"),
        include_str!("../permissions/filesystem_access.toml"),
        include_str!("../permissions/filesystem_export.toml"),
        include_str!("../permissions/project_execution.toml"),
    ] {
        acl_commands.extend(command_permissions_from_commands_allow(src));
    }

    let missing_from_manifest: Vec<_> = acl_commands.difference(&manifest_commands).collect();
    let stale_in_manifest: Vec<_> = manifest_commands.difference(&acl_commands).collect();
    assert!(
        missing_from_manifest.is_empty() && stale_in_manifest.is_empty(),
        "command-security.json elevatedCommands drifted from elevated ACL.\n  missing: {:?}\n  stale: {:?}",
        missing_from_manifest,
        stale_in_manifest,
    );
}

#[test]
fn frontend_invoke_literals_match_registered_commands() {
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repo root");
    let src_dir = repo_root.join("src");
    let mut files = Vec::new();
    fn ts_source_files(dir: &Path, files: &mut Vec<PathBuf>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                ts_source_files(&path, files);
            } else if path
                .extension()
                .is_some_and(|extension| extension == "ts" || extension == "tsx")
            {
                files.push(path);
            }
        }
    }
    ts_source_files(&src_dir, &mut files);

    let registered = app_manifest_command_names();
    let invoke_regex =
        regex::Regex::new(r#"\binvoke(?:\s*<[\s\S]*?>)?\s*\(\s*([^,\n)]+)"#).expect("invoke regex");
    let literal_regex = regex::Regex::new(r#"^["']([a-z0-9_]+)["']$"#).expect("literal regex");
    let mut missing_commands = Vec::new();
    let mut dynamic_calls = Vec::new();

    for file in files {
        let relative = file
            .strip_prefix(repo_root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        if relative.ends_with(".test.ts")
            || relative.ends_with(".test.tsx")
            || relative.ends_with(".spec.ts")
            || relative.ends_with(".spec.tsx")
            || relative.ends_with(".behavior.ts")
            || relative.ends_with(".behavior.tsx")
            || relative.ends_with(".render.ts")
            || relative.ends_with(".render.tsx")
            || relative == "src/lib/tauri-invoke.ts"
            || relative == "src/lib/privileged-command-bridge.ts"
            || relative.starts_with("src/lib/commands/")
        {
            continue;
        }

        let source = std::fs::read_to_string(&file).expect("read frontend source");
        for capture in invoke_regex.captures_iter(&source) {
            let Some(matched) = capture.get(0) else {
                continue;
            };
            let arg = capture
                .get(1)
                .map(|value| value.as_str().trim())
                .unwrap_or("");
            let line = source[..matched.start()].lines().count() + 1;
            let Some(command) = literal_regex
                .captures(arg)
                .and_then(|literal| literal.get(1))
                .map(|value| value.as_str().to_string())
            else {
                dynamic_calls.push(format!("{}:{}", relative, line));
                continue;
            };

            if !registered.contains(&command) {
                missing_commands.push(format!("{}:{} invokes {}", relative, line, command));
            }
        }
    }

    assert!(
        dynamic_calls.is_empty(),
        "Frontend invoke calls must use literal command names so ACL drift is reviewable: {:?}",
        dynamic_calls,
    );
    assert!(
        missing_commands.is_empty(),
        "Frontend invoke calls drifted from registered Tauri commands: {:?}",
        missing_commands,
    );
}

#[test]
fn tracing_instrument_fields_do_not_record_raw_or_secretish_values() {
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);

    let mut findings = Vec::new();
    for file in files {
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        for (line, attribute) in tracing_instrument_attributes(&source) {
            if tracing_field_assignment_is_unsafe(attribute) {
                let relative = file
                    .strip_prefix(env!("CARGO_MANIFEST_DIR"))
                    .unwrap_or(&file)
                    .display();
                findings.push(format!("{}:{}", relative, line));
            }
        }
    }

    assert!(
        findings.is_empty(),
        "tracing::instrument fields must not record raw or secret-like values. Use skip(...) and log parsed safe metadata instead: {:?}",
        findings,
    );
}

/// Files that still read a response body without a byte cap. Every listed
/// file must keep at least one such read, so the list can only shrink as
/// sites move to `http_client::read_json_limited`/`read_text_limited`. It
/// reaches empty in the third body-cap commit and stays empty.
const UNCAPPED_BODY_READ_FILES: &[&str] = &[
    "src/integrations/search_console/analytics.rs",
    "src/integrations/search_console/inspection.rs",
    "src/integrations/search_console/query_comparison.rs",
    "src/integrations/search_console/sites.rs",
    "src/licensing/api.rs",
];

#[test]
fn response_bodies_are_read_only_through_the_limited_readers() {
    let uncapped = regex::Regex::new(r"\.(?:json|text)(?:::<[^>]*>)?\(\)\s*\.await")
        .expect("uncapped read pattern");
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_source_files(&src_dir, &mut files);

    let mut unexpected = Vec::new();
    let mut listed_but_clean: Vec<&str> = UNCAPPED_BODY_READ_FILES.to_vec();
    for file in files {
        let relative = file
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(&file)
            .display()
            .to_string();
        if relative == "src/http_client.rs" || relative.ends_with("_tests.rs") {
            continue;
        }
        let source = std::fs::read_to_string(&file).expect("read Rust source file");
        let hits = uncapped.find_iter(production_half(&source)).count();
        if hits == 0 {
            continue;
        }
        if UNCAPPED_BODY_READ_FILES.contains(&relative.as_str()) {
            listed_but_clean.retain(|listed| *listed != relative);
        } else {
            unexpected.push(format!("{relative} ({hits})"));
        }
    }

    assert!(
        unexpected.is_empty(),
        "Read response bodies through http_client::read_json_limited or read_text_limited with a cap from constants.rs: {:?}",
        unexpected,
    );
    assert!(
        listed_but_clean.is_empty(),
        "These files no longer contain uncapped reads; remove them from UNCAPPED_BODY_READ_FILES so the ratchet only moves toward zero: {:?}",
        listed_but_clean,
    );
}

// Negative control: the pattern sees the turbofish and the multi-line form.
#[test]
fn uncapped_read_guard_detects_every_spelling() {
    let uncapped = regex::Regex::new(r"\.(?:json|text)(?:::<[^>]*>)?\(\)\s*\.await")
        .expect("uncapped read pattern");
    assert!(uncapped.is_match("resp.json().await"));
    assert!(uncapped.is_match("resp.json::<OsvVuln>().await"));
    assert!(uncapped.is_match("resp\n        .text()\n        .await"));
    assert!(!uncapped.is_match(".json(&body).send().await"));
}
