#!/bin/sh
# SiteCMD CLI installer
#
# Usage:
#   curl -fsSL https://sitecmd.com/install.sh | sh
#
# Installs the `sitecmd` binary for macOS (universal) and Linux (x86_64).
# Windows users: download the zip from https://releases.sitecmd.com instead
# (see https://sitecmd.com/docs/cli for the direct link pattern).
#
# Environment overrides:
#   SITECMD_VERSION      install a specific version (default: latest)
#   SITECMD_INSTALL_DIR  target directory (default: /usr/local/bin if
#                        writable, otherwise ~/.local/bin)
#
# Every artifact ships with checksum and minisign sidecars generated by the
# release pipeline. This script verifies both before installing.
#
# All work happens inside main(), which runs only after the whole file has
# been read, so a connection that drops mid-download executes nothing.

set -eu

RELEASES_HOST="https://releases.sitecmd.com"
MINISIGN_PUBLIC_KEY="RWTtzNh0gmMU/8O1AJBbQbUEy9oD5lpqL/dV0qRqlpsCldfWNWgxr5kE"
SEMVER_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.-]+)?$'

fail() {
  echo "sitecmd-install: error: $1" >&2
  exit 1
}

minisign_hint() {
  case "$(uname -s)" in
    Darwin) echo "  brew install minisign" ;;
    Linux)
      if command -v apt-get >/dev/null 2>&1; then echo "  sudo apt-get install minisign"
      elif command -v dnf >/dev/null 2>&1; then echo "  sudo dnf install minisign"
      elif command -v pacman >/dev/null 2>&1; then echo "  sudo pacman -S minisign"
      elif command -v apk >/dev/null 2>&1; then echo "  sudo apk add minisign"
      else echo "  https://jedisct1.github.io/minisign/#installation"
      fi
      ;;
    *) echo "  https://jedisct1.github.io/minisign/#installation" ;;
  esac
}

require_minisign() {
  command -v minisign >/dev/null 2>&1 && return 0
  echo "sitecmd-install: error: minisign is required to authenticate the release. Install it with:" >&2
  minisign_hint >&2
  exit 1
}

fetch() {
  curl --fail --silent --show-error --location --retry 3 \
    --proto '=https' --tlsv1.2 "$@"
}

decode_signature() {
  encoded=$1
  decoded=$2
  compact="$decoded.b64"
  tr -d '\r\n' < "$encoded" > "$compact"

  if printf '' | base64 --decode >/dev/null 2>&1; then
    base64 --decode < "$compact" > "$decoded"
  elif printf '' | base64 -D >/dev/null 2>&1; then
    base64 -D < "$compact" > "$decoded"
  elif command -v openssl >/dev/null 2>&1; then
    openssl base64 -d -A -in "$compact" -out "$decoded"
  else
    fail "base64 or openssl is required to decode the release signature"
  fi
}

# True when $1 sorts before $2 by MAJOR.MINOR.PATCH; both were validated already.
version_is_older() {
  left=${1%%[-+]*}
  right=${2%%[-+]*}
  old_ifs=$IFS
  IFS=.
  set -- $left $right
  IFS=$old_ifs
  [ "$1" -lt "$4" ] && return 0
  [ "$1" -gt "$4" ] && return 1
  [ "$2" -lt "$5" ] && return 0
  [ "$2" -gt "$5" ] && return 1
  [ "$3" -lt "$6" ]
}

detect_target() {
  os=$(uname -s)
  arch=$(uname -m)
  case "$os" in
    Darwin)
      target="darwin-universal"
      ;;
    Linux)
      case "$arch" in
        x86_64 | amd64) target="linux-x86_64" ;;
        *) fail "no prebuilt CLI for Linux/$arch yet (x86_64 only). Contact support@sitecmd.com if you need this platform." ;;
      esac
      ;;
    MINGW* | MSYS* | CYGWIN*)
      fail "on Windows, download the zip from $RELEASES_HOST (see https://sitecmd.com/docs/cli)"
      ;;
    *)
      fail "unsupported platform: $os"
      ;;
  esac
}

resolve_install_dir() {
  install_dir="${SITECMD_INSTALL_DIR:-}"
  if [ -z "$install_dir" ]; then
    if [ -d /usr/local/bin ] && [ -w /usr/local/bin ]; then
      install_dir="/usr/local/bin"
    else
      install_dir="$HOME/.local/bin"
    fi
  fi
}

resolve_version() {
  pinned_version="${SITECMD_VERSION:-}"
  version="$pinned_version"
  if [ -z "$version" ]; then
    # The releases worker's root route reports {"latest_version":"x.y.z",...}.
    version=$(fetch "$RELEASES_HOST/" | sed -n 's/.*"latest_version":"\([^"]*\)".*/\1/p')
    [ -n "$version" ] || fail "could not determine the latest version from $RELEASES_HOST"
  fi
  printf '%s\n' "$version" | grep -Eq "$SEMVER_PATTERN" \
    || fail "invalid release version: $version"
}

# An unauthenticated "latest" answer must never move an installed CLI backwards.
refuse_downgrade() {
  [ -z "$pinned_version" ] || return 0
  [ -x "$install_dir/sitecmd" ] || return 0
  installed_version=$("$install_dir/sitecmd" --version 2>/dev/null | sed -n 's/^sitecmd //p')
  printf '%s\n' "$installed_version" | grep -Eq "$SEMVER_PATTERN" || return 0
  if version_is_older "$version" "$installed_version"; then
    fail "the latest published release ($version) is older than the installed sitecmd $installed_version; refusing to downgrade. Set SITECMD_VERSION=$version to install it anyway."
  fi
}

main() {
  command -v curl >/dev/null 2>&1 || fail "curl is required"
  command -v tar >/dev/null 2>&1 || fail "tar is required"
  command -v grep >/dev/null 2>&1 || fail "grep is required"
  require_minisign

  detect_target
  resolve_install_dir
  resolve_version
  refuse_downgrade

  archive="sitecmd-cli_${version}_${target}.tar.gz"
  url="$RELEASES_HOST/v${version}/${archive}"

  tmpdir=$(mktemp -d)
  install_candidate=
  cleanup() {
    rm -rf "$tmpdir"
    if [ -n "$install_candidate" ]; then
      rm -f "$install_candidate"
    fi
  }
  trap cleanup EXIT

  echo "Downloading sitecmd ${version} (${target})..."
  fetch --output "$tmpdir/$archive" "$url" || fail "download failed: $url"
  fetch --output "$tmpdir/$archive.sha256" "$url.sha256" || fail "checksum download failed: $url.sha256"
  fetch --output "$tmpdir/$archive.sig" "$url.sig" || fail "signature download failed: $url.sig"

  decode_signature "$tmpdir/$archive.sig" "$tmpdir/$archive.minisig"
  minisign -Vm "$tmpdir/$archive" \
    -x "$tmpdir/$archive.minisig" \
    -P "$MINISIGN_PUBLIC_KEY" >/dev/null \
    || fail "signature verification failed for $archive"

  expected_sha256=$(sed -n '1{s/[[:space:]].*$//;p;}' "$tmpdir/$archive.sha256" | tr 'A-F' 'a-f')
  printf '%s\n' "$expected_sha256" | grep -Eq '^[0-9a-f]{64}$' \
    || fail "checksum sidecar did not contain one SHA-256 digest"
  if command -v sha256sum >/dev/null 2>&1; then
    actual_sha256=$(sha256sum "$tmpdir/$archive")
  elif command -v shasum >/dev/null 2>&1; then
    actual_sha256=$(shasum -a 256 "$tmpdir/$archive")
  else
    fail "sha256sum or shasum is required to verify the download"
  fi
  actual_sha256=${actual_sha256%% *}
  [ "$actual_sha256" = "$expected_sha256" ] \
    || fail "checksum verification failed for $archive"

  tar -xzf "$tmpdir/$archive" -C "$tmpdir"
  [ -f "$tmpdir/sitecmd" ] || fail "archive did not contain the sitecmd binary"
  chmod 0755 "$tmpdir/sitecmd"
  if ! actual_version=$("$tmpdir/sitecmd" --version 2>/dev/null); then
    fail "downloaded CLI could not report its version"
  fi
  [ "$actual_version" = "sitecmd $version" ] \
    || fail "downloaded CLI reported '$actual_version', expected 'sitecmd $version'"

  mkdir -p "$install_dir"
  install_candidate=$(mktemp "$install_dir/.sitecmd.XXXXXX")
  cp "$tmpdir/sitecmd" "$install_candidate"
  chmod 0755 "$install_candidate"
  mv "$install_candidate" "$install_dir/sitecmd"
  install_candidate=

  echo "Installed $actual_version to $install_dir/sitecmd"

  case ":$PATH:" in
    *":$install_dir:"*) ;;
    *)
      echo ""
      echo "Note: $install_dir is not on your PATH. Add it with:"
      echo "  export PATH=\"$install_dir:\$PATH\""
      ;;
  esac
}

main "$@"
