//! Command substrings recognized as quality gates in CI workflows and commit hooks.

pub(super) const QUALITY_GATE_MARKERS: &[&str] = &[
    "npm test",
    "npm run test",
    "npm run build",
    "npm run lint",
    "npm run typecheck",
    "npm run type-check",
    "npm run check",
    "npm run e2e",
    "pnpm test",
    "pnpm build",
    "pnpm lint",
    "pnpm typecheck",
    "pnpm type-check",
    "pnpm check",
    "pnpm e2e",
    "pnpm run test",
    "pnpm run build",
    "pnpm run lint",
    "pnpm run typecheck",
    "pnpm run type-check",
    "pnpm run check",
    "pnpm run e2e",
    "yarn test",
    "yarn build",
    "yarn lint",
    "yarn typecheck",
    "yarn type-check",
    "yarn e2e",
    "bun test",
    "bun run test",
    "bun run build",
    "bun run lint",
    "bun run typecheck",
    "bun run type-check",
    "bun run check",
    "bun run e2e",
    "next build",
    "vite build",
    "astro build",
    "astro check",
    "nuxt build",
    "nuxi typecheck",
    "nuxt typecheck",
    "svelte-check",
    "vue-tsc",
    "react-scripts build",
    "tsc",
    "npx tsc",
    "eslint",
    "biome check",
    "biome ci",
    "biome lint",
    "oxlint",
    "stylelint",
    "prettier --check",
    "prettier -c",
    // Staged-file formatters are the usual pre-commit gate.
    "prettier",
    "pretty-quick",
    "lint-staged",
    "nano-staged",
    "biome format",
    "dprint",
    "rustfmt",
    "black",
    "isort",
    "ruff format",
    "php-cs-fixer",
    "phpcbf",
    "pint",
    "vitest",
    "jest",
    "mocha",
    "ava",
    "node --test",
    "deno test",
    "deno lint",
    "deno check",
    "web-test-runner",
    "wdio",
    "playwright test",
    "cypress run",
    "pytest",
    "python -m pytest",
    "python -m unittest",
    "tox",
    "nox",
    "ruff check",
    "ruff format --check",
    "flake8",
    "black --check",
    "mypy",
    "pyright",
    "pylint",
    "bandit",
    "cargo test",
    "cargo nextest",
    "cargo check",
    "cargo clippy",
    "cargo fmt --check",
    "cargo fmt -- --check",
    "go test",
    "go vet",
    "golangci-lint",
    "gofmt",
    "staticcheck",
    "dotnet test",
    "flutter test",
    "dart test",
    "phpunit",
    "pest",
    "psalm",
    "phpcs",
    "phpstan analyse",
    "phpstan analyze",
    "pint --test",
    "php artisan test",
    "composer test",
    "composer lint",
    "composer check",
    "composer analyse",
    "composer analyze",
    "composer phpstan",
    "composer pint",
    "composer cs",
    "vendor/bin/phpunit",
    "vendor/bin/pest",
    "vendor/bin/pint",
    "vendor/bin/phpstan",
    "vendor/bin/phpcs",
    "vendor/bin/psalm",
    "vendor/bin/php-cs-fixer",
    "vendor/bin/rector",
    "rspec",
    "bundle exec rspec",
    "rails test",
    "rubocop",
    "make test",
    "make build",
    "make check",
    "make lint",
    "sitecmd check",
    "sitecmd audit",
    "sitecmd scan",
    // Monorepo task runners: CI usually invokes quality scripts through
    // turbo/nx rather than npm run directly.
    "turbo run build",
    "turbo run lint",
    "turbo run test",
    "turbo run typecheck",
    "turbo run check",
    "turbo build",
    "turbo lint",
    "turbo test",
    "turbo typecheck",
    "nx run-many",
    "nx affected",
    "nx build",
    "nx test",
    "nx lint",
];

/// The subset of gate commands that execute a test suite.
pub(super) const TEST_GATE_MARKERS: &[&str] = &[
    "npm test",
    "npm t",
    "npm run test",
    "npm run -s test",
    "npm run --silent test",
    "npm run --if-present test",
    "npm run e2e",
    "pnpm test",
    "pnpm run test",
    "pnpm run --if-present test",
    "pnpm e2e",
    "pnpm run e2e",
    "yarn test",
    "yarn run test",
    "yarn e2e",
    "bun test",
    "bun run test",
    "bun run e2e",
    "vitest",
    "jest",
    "mocha",
    "ava",
    "node --test",
    "deno test",
    "web-test-runner",
    "wdio",
    "playwright test",
    "cypress run",
    "pytest",
    "python -m pytest",
    "python -m unittest",
    "tox",
    "nox",
    "cargo test",
    "cargo nextest",
    "go test",
    "dotnet test",
    "flutter test",
    "dart test",
    "phpunit",
    "pest",
    "vendor/bin/phpunit",
    "vendor/bin/pest",
    "php artisan test",
    "composer test",
    "rspec",
    "bundle exec rspec",
    "rails test",
    "make test",
    "turbo run test",
    "turbo test",
    "nx test",
    "nx run-many",
    "nx affected",
];

/// Commands inside a package script that make it a lint or typecheck script.
pub(super) const LINT_COMMAND_MARKERS: &[&str] = &[
    "eslint",
    "biome",
    "tsc",
    "oxlint",
    "stylelint",
    "prettier --check",
    "prettier -c",
    "astro check",
    "svelte-check",
    "vue-tsc",
    "nuxi typecheck",
    "pint",
    "phpstan",
    "phpcs",
    "psalm",
    "php-cs-fixer",
    "rector",
    "ruff",
    "flake8",
    "mypy",
    "pyright",
    "pylint",
    "clippy",
    "golangci-lint",
    "rubocop",
    "deno lint",
    "deno check",
];

fn is_word_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_'
}

/// Substring match bounded on word characters, so `jest` matches `jest --ci`
/// and `vendor/bin/phpunit` but not `majestic`. A marker that starts or ends
/// in a space or punctuation carries its own boundary on that side.
pub(super) fn contains_marker(lower: &str, marker: &str) -> bool {
    if marker.is_empty() {
        return false;
    }
    let bytes = lower.as_bytes();
    let check_left = marker.as_bytes()[0].is_ascii_alphanumeric();
    let check_right = marker.as_bytes()[marker.len() - 1].is_ascii_alphanumeric();
    let mut start = 0;
    while let Some(found) = lower[start..].find(marker) {
        let index = start + found;
        let end = index + marker.len();
        let left_ok = !check_left || index == 0 || !is_word_byte(bytes[index - 1]);
        let right_ok = !check_right || end >= bytes.len() || !is_word_byte(bytes[end]);
        if left_ok && right_ok {
            return true;
        }
        // The marker starts with an ASCII byte, so index + 1 stays on a char
        // boundary.
        start = index + 1;
    }
    false
}

pub(super) fn contains_any_marker(lower: &str, markers: &[&str]) -> bool {
    markers.iter().any(|marker| contains_marker(lower, marker))
}
