//! Command substrings recognized as quality gates in CI workflows and commit hooks.

pub(super) const QUALITY_GATE_MARKERS: &[&str] = &[
    "npm test",
    "npm run test",
    "npm run build",
    "npm run lint",
    "npm run typecheck",
    "npm run type-check",
    "pnpm test",
    "pnpm build",
    "pnpm lint",
    "pnpm typecheck",
    "pnpm type-check",
    "pnpm run test",
    "pnpm run build",
    "pnpm run lint",
    "pnpm run typecheck",
    "pnpm run type-check",
    "yarn test",
    "yarn build",
    "yarn lint",
    "yarn typecheck",
    "yarn type-check",
    "bun test",
    "bun run test",
    "bun run build",
    "bun run lint",
    "bun run typecheck",
    "bun run type-check",
    "next build",
    "vite build",
    "astro build",
    "nuxt build",
    "react-scripts build",
    "tsc ",
    "tsc --",
    "eslint ",
    "biome check",
    "biome ci",
    "lint-staged",
    "vitest",
    "jest",
    "playwright test",
    "cypress run",
    "pytest",
    "ruff check",
    "mypy",
    "cargo test",
    "cargo check",
    "cargo clippy",
    "go test",
    "go vet",
    "dotnet test",
    "flutter test",
    "dart test",
    "phpunit",
    "rspec",
    "bundle exec rspec",
    "make test",
    "make build",
    "make check",
    // Monorepo task runners: CI usually invokes quality scripts through
    // turbo/nx rather than npm run directly.
    "turbo run build",
    "turbo run lint",
    "turbo run test",
    "turbo run typecheck",
    "turbo run check",
    "turbo build",
    "turbo lint",
    "turbo test",
    "turbo typecheck",
    "nx run-many",
    "nx affected",
    "nx build",
    "nx test",
    "nx lint",
];
