pub(in crate::core::code_scan) static SUPPLY_CHAIN_UNUSED_IGNORE_PREFIXES: &[&str] = &[
    "@types/",
    "@vitejs/",
    "@storybook/",
    "@testing-library/",
    "@vitest/",
    "@size-limit/",
    "@babel/",
    "babel-",
    "@swc/",
    "swc-",
    "@rollup/",
    "rollup-plugin-",
    "@webpack-cli/",
    "webpack-cli",
    "webpack-dev-",
    "eslint-",
    "@eslint/",
    "@eslint-community/",
    "prettier-",
    "@prettier/",
    "stylelint-",
    "@stylelint/",
    "postcss-",
    "@postcss/",
    "@biomejs/",
    "sass-",
    "@parcel/",
    "parcel-",
    "esbuild-",
    "@esbuild/",
    "@next/",
    "gulp-",
    "@gulp-",
    "grunt-",
];

pub(in crate::core::code_scan) static SUPPLY_CHAIN_UNUSED_IGNORE_EXACT: &[&str] = &[
    // Core TypeScript / JS toolchain
    "typescript",
    "tsx",
    "ts-node",
    "ts-loader",
    "esbuild",
    "swc",
    // Bundlers
    "vite",
    "webpack",
    "rollup",
    "parcel",
    "snowpack",
    "esbuild",
    "turbopack",
    // Test runners + infra
    "vitest",
    "jest",
    "playwright",
    "cypress",
    "storybook",
    "jsdom",
    "happy-dom",
    "c8",
    "nyc",
    "mocha",
    "chai",
    "ava",
    // Linters / formatters (CLI-only, not imported)
    "eslint",
    "prettier",
    "biome",
    "stylelint",
    "markdownlint",
    "htmlhint",
    "oxlint",
    // CSS toolchain
    "postcss",
    "autoprefixer",
    "tailwindcss",
    "sass",
    "sass-loader",
    "node-sass",
    "less",
    "less-loader",
    "stylus",
    // DX tools (run as CLI from npm scripts)
    "nodemon",
    "cross-env",
    "rimraf",
    "concurrently",
    "npm-run-all",
    "npm-run-all2",
    "pm2",
    "forever",
    "dotenv-cli",
    "chokidar-cli",
    "serve",
    "http-server",
    "browser-sync",
    "live-server",
    // Git hooks
    "turbo",
    "husky",
    "lint-staged",
    "simple-git-hooks",
    "commitizen",
    "cz-conventional-changelog",
    "@commitlint/cli",
    "@commitlint/config-conventional",
    // Package-provided CLIs invoked through package scripts or release tooling.
    // They are executable dependencies and are not expected to be imported.
    "@tauri-apps/cli",
    "@cloudflare/workers-types",
    "wrangler",
    // Drupal-specific build CLIs
    "drupal-radix-cli",
];
