import { StyleSheet } from "@/lib/react-pdf-browser";

export const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1a1a1a",
    backgroundColor: "#ffffff",
  },
  titlePage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  siteUrl: {
    fontSize: 11,
    color: "#666",
    marginBottom: 8,
  },
  reportTitle: {
    fontSize: 28,
    fontFamily: "Helvetica-Bold",
    color: "#111",
    marginBottom: 6,
    textAlign: "center",
  },
  periodLabel: {
    fontSize: 11,
    color: "#888",
    marginBottom: 24,
  },
  scoreCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  scoreValue: {
    fontSize: 32,
    fontFamily: "Helvetica-Bold",
    color: "#fff",
  },
  scoreTrend: {
    fontSize: 12,
    marginBottom: 4,
  },
  generatedAt: {
    fontSize: 9,
    color: "#999",
    marginTop: 40,
  },
  companyName: {
    fontSize: 10,
    color: "#666",
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: "#111",
    marginBottom: 12,
    marginTop: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
  },
  summaryRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 16,
  },
  summaryBox: {
    flex: 1,
    padding: 12,
    borderRadius: 4,
    backgroundColor: "#f8f8f8",
    alignItems: "center",
  },
  summaryValue: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    marginBottom: 2,
  },
  summaryLabel: {
    fontSize: 8,
    color: "#888",
    textTransform: "uppercase",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f3f3",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 3,
    marginBottom: 2,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  tableCell: {
    fontSize: 10,
  },
  issueRow: {
    marginBottom: 8,
    padding: 8,
    borderLeftWidth: 3,
    borderRadius: 2,
    backgroundColor: "#fafafa",
  },
  issueTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 2,
  },
  issueDesc: {
    fontSize: 9,
    color: "#555",
    lineHeight: 1.4,
  },
  issueMeta: {
    flexDirection: "row",
    gap: 8,
    marginTop: 3,
  },
  badge: {
    fontSize: 8,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 2,
    color: "#fff",
    fontFamily: "Helvetica-Bold",
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: "#bbb",
  },
});
